### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by dhleong** [dhleong/judo#19]
Probably with raw/ansi/html modes, possibly with some builtins for picking the destination file, and whether to append or replace files

**Comment by ttpro1995** [comment]
hi @dhleong , how to use logging feature  ? 
Do you have any documentation  ?

**Comment by dhleong** [comment]
@ttpro1995 The only real documentation is with the in-app help system: `:help logToFile`. For a more complete example, I uploaded some code here: 

https://github.com/dhleong/judo/blob/master/docs/examples/logging.py

Hope this helps!

**Comment by ttpro1995** [comment]
I still don't get it. This is the app, why do I need example code ? 
How to make Judo log everything on-screen (mud game) to file ?

**Comment by dhleong** [comment]
As explained in the Readme, Judo is configured via scripts. This is similar
to another well-known CLI MUD client, tintin++. But with Judo, you can use
a well-known language instead of a custom one---in this case, Python.

The first half of the code is intended to be placed in
~/.config/judo/init.py so it can be reused if you have multiple servers you
play on. The second half is intended to be in the script to connect to a
specific world; the init.py file will be loaded automatically. This
behavior is inspired by vim.

**Comment by ttpro1995** [comment]
Please write a document on Scripting

**Comment by dhleong** [comment]
@ttpro1995 There's already one right here: https://github.com/dhleong/judo/blob/master/docs/Scripting.md

 :)
